#pragma once

#include <stdint.h>

typedef struct cbodu_state cbodu_state;
typedef void (*cbodu_fn)(cbodu_state*);

extern uint64_t cbodu_number(cbodu_state*, int64_t);
extern uint64_t cbodu_float(cbodu_state*, double);
extern uint64_t cbodu_string(cbodu_state*, const char*);
extern uint64_t cbodu_boolean(cbodu_state*, uint8_t);
extern uint64_t cbodu_null(cbodu_state*);
extern uint8_t cbodu_iserr(cbodu_state*);
extern uint64_t cbodu_geterr(cbodu_state*);
extern void cbodu_seterr(cbodu_state*, uint64_t);
extern void cbodu_setret(cbodu_state*, uint64_t);
extern uint64_t cbodu_getinternal(cbodu_state*, uint64_t);
extern uint64_t cbodu_argslen(cbodu_state*);
extern uint64_t cbodu_getarg(cbodu_state*, uint64_t);
extern const char* cbodu_tostring(cbodu_state*, uint64_t);
extern int64_t cbodu_tonumber(cbodu_state*, uint64_t);
extern double cbodu_tofloat(cbodu_state*, uint64_t);
extern uint8_t cbodu_toboolean(cbodu_state*, uint64_t);
extern uint64_t cbodu_newobject(cbodu_state*);
extern uint64_t cbodu_get(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_set(cbodu_state*, uint64_t, uint64_t, uint64_t);
extern uint64_t cbodu_obj_getmetaobj(cbodu_state*, uint64_t);
extern uint64_t cbodu_obj_setmetaobj(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_obj_makegetset(cbodu_state*, uint64_t, uint64_t, uint64_t, uint64_t);
extern uint64_t cbodu_obj_getinternal(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_obj_setinternal(cbodu_state*, uint64_t, uint64_t, uint64_t);
extern uint64_t cbodu_newfn(cbodu_state*, cbodu_fn);
extern uint64_t cbodu_setinternal(cbodu_state*, uint64_t, uint64_t, uint64_t);
extern uint64_t cbodu_add(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_subtract(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_multiply(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_divide(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_remainder(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_negate(cbodu_state*, uint64_t);
extern uint64_t cbodu_eql(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_neql(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_not(cbodu_state*, uint64_t);
extern uint64_t cbodu_gt(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_ge(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_lt(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_le(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_and(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_or(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_xor(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_vec_new(cbodu_state*);
extern void cbodu_vec_push(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_vec_pop(cbodu_state*, uint64_t);
extern uint64_t cbodu_vec_len(cbodu_state*, uint64_t);
extern uint64_t cbodu_vec_get(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_call(cbodu_state*, uint64_t, uint64_t);
extern uint8_t cbodu_debug(cbodu_state*);
extern uint64_t cbodu_orthat(cbodu_state*, uint64_t, uint64_t);
extern uint64_t cbodu_isntnull(cbodu_state*, uint64_t);
extern uint64_t cbodu_maketuple(cbodu_state*, uint64_t);
extern uint64_t cbodu_detuple(cbodu_state*, uint64_t);
extern void cbodu_clearerr(cbodu_state*);
extern uint64_t cbodu_getregister(cbodu_state*, const char*);